filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
