// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/newer027/kratos_microservice/apps/products/internal/dao"
	"github.com/newer027/kratos_microservice/apps/products/internal/server/http"
	"github.com/newer027/kratos_microservice/apps/products/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	daoDao, cleanup4, err := dao.New()
	if err != nil {
		return nil, nil, err
	}
	serviceService, cleanup5, err := service.New(daoDao)
	if err != nil {
		cleanup4()
		return nil, nil, err
	}
	engine, err := http.New(serviceService)
	if err != nil {
		cleanup5()
		cleanup4()
		return nil, nil, err
	}
	app, cleanup6, err := NewApp(serviceService, engine)
	if err != nil {
		cleanup5()
		cleanup4()
		return nil, nil, err
	}
	return app, func() {
		cleanup6()
		cleanup5()
		cleanup4()
	}, nil
}
