{
 "title": "details",
 "tags": [ "go" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Base",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of instances",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(up{job=\"details\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_goroutines",
     "type": "graph",
     "description": "Number of goroutines that currently exist",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes",
     "type": "graph",
     "description": "Number of bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes_total",
     "type": "graph",
     "description": "Total number of bytes allocated, even if freed",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_buck_hash_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used by the profiling bucket hash table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_cpu_fraction",
     "type": "graph",
     "description": "The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_frees_total",
     "type": "graph",
     "description": "Total number of frees",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_frees_total{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_alloc_bytes",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for garbage collection system metadata",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_inuse_bytes",
     "type": "graph",
     "description": "Number of heap bytes that are in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_idle_bytes",
     "type": "graph",
     "description": "Number of heap bytes waiting to be used",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_released_bytes",
     "type": "graph",
     "description": "Number of heap bytes released to OS",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_objects",
     "type": "graph",
     "description": "Number of allocated objects",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_last_gc_time_seconds",
     "type": "graph",
     "description": "Number of seconds since 1970 of last garbage collection",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_sys_bytes",
     "type": "graph",
     "description": "Number of heap bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mallocs_total",
     "type": "graph",
     "description": "Total number of mallocs",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_lookups_total",
     "type": "graph",
     "description": "Total number of pointer lookups",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_lookups_total{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mcache structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mcache structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mspan structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mspan structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_other_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for other system allocations",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_next_gc_bytes",
     "type": "graph",
     "description": "Number of heap bytes when next garbage collection will take place",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system for stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by the stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 132 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"details\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc server 99%-tile Latency of requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of grpc server request group by (instance)",
     "type": "graph",
     "description": "Latency of grpc server request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98999999999999999,sum(rate(grpc_server_requests_duration_ms_bucket{job=\"details\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client 99%-tile Latency of requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of grpc client request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grpc_client_requests_duration_ms_bucket{le=\"10\"}",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of http[\"grpc_code\"] request group by (grpc_code) per seconds",
     "type": "graph",
     "description": "Number of http[\"grpc_code\"] request group by (grpc_code) per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_duration_ms_count[1m])) by (path)"
      }
     ]
    }
   ]
  }
 ]
}