[Client]
	addr = "db:3306"
	dsn = "products:123456@tcp(db:3306)/products?parseTime=True&loc=Local&timeout=10s&readTimeout=10s&writeTimeout=10s&charset=utf8mb4,utf8"
	readDSN = ["products:123456@tcp(db:3306)/products?parseTime=True&loc=Local&timeout=10s&readTimeout=10s&writeTimeout=10s&charset=utf8mb4,utf8"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "2000ms"
	execTimeout = "3000ms"
	tranTimeout = "4000ms"
