version: "3.7"

services:
  db:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - TZ=Asia/Shanghai
    volumes:
    - .:/docker-entrypoint-initdb.d
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci'
    ]

  redis:
    image: redis
    ports:
      - 6379:6379

  memcached:
    image: memcached
    ports:
      - 11211:11211 